<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analizis Estadistoco Vuelos NYC 2023.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Analizis aereolineas_files/libs/clipboard/clipboard.min.js"></script>
<script src="Analizis aereolineas_files/libs/quarto-html/quarto.js"></script>
<script src="Analizis aereolineas_files/libs/quarto-html/popper.min.js"></script>
<script src="Analizis aereolineas_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Analizis aereolineas_files/libs/quarto-html/anchor.min.js"></script>
<link href="Analizis aereolineas_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Analizis aereolineas_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Analizis aereolineas_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Analizis aereolineas_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Analizis aereolineas_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analizis Estadistoco Vuelos NYC 2023.</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduccion" class="level2">
<h2 class="anchored" data-anchor-id="introduccion">INTRODUCCION</h2>
<p>El presente análisis estadístico desglosa la operación de los aeropuertos de la ciudad de Nueva York durante el año 2023, un periodo caracterizado por la recuperación total de la demanda aérea tras la pandemia y retos significativos en la infraestructura aeroportuaria y el control del tráfico aéreo. A través del uso de diversas métricas de tendencia central, dispersión y forma, este estudio busca trascender los simples promedios para revelar la verdadera experiencia del pasajero y la eficiencia de las aerolíneas en uno de los espacios aéreos más congestionados del mundo</p>
</section>
<section id="objetivo-general" class="level2">
<h2 class="anchored" data-anchor-id="objetivo-general">Objetivo General</h2>
<p>Evaluar el rendimiento operativo y la puntualidad de los vuelos en Nueva York mediante herramientas estadísticas avanzadas, permitiendo identificar patrones estacionales, ineficiencias en el sistema de transporte y la variabilidad crítica entre las principales operadoras aéreas.</p>
</section>
<section id="planteamiento-del-problema" class="level2">
<h2 class="anchored" data-anchor-id="planteamiento-del-problema">Planteamiento del Problema</h2>
<p>Durante el año 2023, el sistema aeroportuario de la ciudad de Nueva York se enfrentó a una presión operativa sin precedentes, marcada por el retorno masivo del turismo y los viajes de negocios tras la estabilidad post-pandemia, sin embargo, esta alta demanda de casi&nbsp;<strong>40,000 vuelos mensuales</strong>&nbsp;en periodos pico como marzo, chocó directamente con una infraestructura limitada, una escasez crítica de controladores aéreos por parte de la FAA y fenómenos climáticos extremos.</p>
<p>El problema central radica en que, aunque la red aérea de NYC está diseñada para trayectos regionales eficientes (con una mediana de&nbsp;<strong>121 minutos</strong>), la realidad estadística muestra una variabilidad extrema y una falta de predictibilidad que penaliza severamente al usuario. El uso de promedios simples en los informes oficiales oculta la gravedad de los retrasos reflejados en una&nbsp;<strong>media cuadrática de 93.04</strong>&nbsp;y en niveles de&nbsp;<strong>curtosis</strong>&nbsp;alarmantes para aerolíneas como Frontier y JetBlue. Existe, por tanto, una desconexión entre el itinerario programado y la ejecución real de los vuelos, lo que genera una ineficiencia económica y logística que este análisis busca cuantificar y explicar mediante la descomposición de datos de tendencia central,</p>
</section>
<section id="preguntas-problema" class="level2">
<h2 class="anchored" data-anchor-id="preguntas-problema">Preguntas Problema</h2>
<p><strong>Preguntas de Investigación</strong></p>
<p>A lo largo de este análisis, se darán respuesta a las siguientes interrogantes:</p>
<p>1.&nbsp;&nbsp;&nbsp; <strong>¿Cuál es la duración y distancia real</strong>&nbsp;de un vuelo típico en Nueva York cuando eliminamos el ruido de los valores extremos?</p>
<p>2.&nbsp;&nbsp;&nbsp; <strong>¿Qué tan representativo es el promedio de tiempo de vuelo</strong>&nbsp;frente a la mediana en un entorno de alta congestión?</p>
<p>3.&nbsp;&nbsp;&nbsp; <strong>¿Cómo influye la estacionalidad de marzo</strong>&nbsp;en el volumen total de operaciones anuales y qué factores sociales lo explican?</p>
<p>4.&nbsp;&nbsp;&nbsp; <strong>¿Cuál es la velocidad de progresión real (media armónica)</strong>&nbsp;de los aviones considerando las demoras en pista y aproximación?</p>
<p>5.&nbsp;&nbsp;&nbsp; <strong>¿Qué tan severos son los retrasos extremos</strong>&nbsp;en el sistema cuando se analizan bajo una media cuadrática que penaliza las fallas graves?</p>
<p>6.&nbsp;&nbsp;&nbsp; <strong>¿Existe una diferencia significativa en la predictibilidad</strong>&nbsp;de los horarios entre una aerolínea de bajo costo como Frontier y una de red masiva como JetBlue?</p>
<p>7.&nbsp;&nbsp;&nbsp; <strong>¿Cuál es el peso real de los “vuelos de cola larga”</strong>&nbsp;(transatlánticos) sobre las estadísticas de una red predominantemente regional?</p>
<p>8.&nbsp;&nbsp;&nbsp; <strong>¿Qué tan probable es sufrir un retraso fuera de lo común</strong>&nbsp;basándonos en los niveles de curtosis observados en 2023?</p>
<p>9.&nbsp;&nbsp;&nbsp; <strong>¿En qué medida la escasez de controladores aéreos y el clima</strong>&nbsp;afectaron la asimetría de los tiempos de vuelo?</p>
<p>10. <strong>¿Cuál es el perfil de riesgo y confiabilidad</strong>&nbsp;que presentan las aerolíneas con base en su coeficiente de variación y desviación estándar?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"nycflights23"</span>)) <span class="fu">install.packages</span>(<span class="st">"nycflights23"</span>, <span class="at">repos =</span> <span class="st">"https://cran.rstudio.com/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nycflights23</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'nycflights23' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nycflights23)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nycflights23)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Iniciamos este estudio dando respuesta a la primera pregunta de investigación, para esto usamos la función na.rm ya que en esta base de datos tambien hay vuelos cancelados con valores NA, por ende si no quitamos esos valores vacíos, R no podrá hacer la suma y nos devolverá un error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Tiempo_promedio_vuelo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(flights<span class="sc">$</span>air_time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El Tiempo Promedio de Vuelo Fue:"</span>, Tiempo_promedio_vuelo, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El Tiempo Promedio de Vuelo Fue: 141.8203 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Distancia_promedio <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(flights<span class="sc">$</span>distance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Distancia Recorrida en Promedio Fue:"</span>, Distancia_promedio, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Distancia Recorrida en Promedio Fue: 977.503 </code></pre>
</div>
</div>
<p>Para entender estas cifras promedio, primero debemos contextualizar la geografía operativa de Nueva York. Un tiempo promedio de 141.82 minutos (unas 2 horas y 22 minutos) y una distancia de 977.5 millas sitúan el flujo principal de los aeropuertos de NYC (JFK, LGA, EWR) en el corredor doméstico de media distancia. Estadísticamente, esto nos indica que la mayor parte de los vuelos de la ciudad de Nueva York no fueron transcontinentales ni a ciudades vecinas, sino las rutas hacia el Medio Oeste (Chicago) y el Sureste (Florida/Atlanta) nos permite afirmar que a estas distancias es donde el avión sigue siendo más competitivo que el tren o el coche en la costa este de los Estados Unidos.</p>
<p>En el ámbito social, el fenómeno del “Revenge Travel” (viajes de revancha tras la pandemia) alcanzó su punto máximo en 2023. La saturación de las terminales y las pistas en Nueva York, que operan bajo un sistema de&nbsp;<em>slots</em>&nbsp;(turnos) muy rígido, significa que esos 141 minutos de promedio incluyen una cantidad significativa de tiempo de rodaje en pista y esperas en el aire. Socialmente, el pasajero neoyorquino se ha adaptado a que un vuelo de 800 millas tarde más de dos horas debido a la congestión crónica de la infraestructura, lo que refleja una ineficiencia aceptada en el sistema de transporte más importante del país.</p>
<p>Ahora bien como bien sabemos el promedio aritmético puede ser muy sensible a valores “valores atípicos” o&nbsp;<em>outliers</em>; por ejemplo, un solo vuelo que se quede atrapado tres horas en la pista de JFK debido a una tormenta invernal o un fallo técnico disparará el promedio de tiempo, aunque el resto de los vuelos hayan salido a tiempo. Por esta razón, para entender realmente qué experimenta el pasajero “típico” y eliminar el ruido de los eventos extremos, es fundamental calcular la&nbsp;<strong>mediana</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Mediana_tiempo_de_vuelo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">median</span>(flights<span class="sc">$</span>air_time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Mediana de Tempo de Vuelo Fue:"</span>, Mediana_tiempo_de_vuelo, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Mediana de Tempo de Vuelo Fue: 121 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Mediana_Distancia_de_vuelo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">median</span>(flights<span class="sc">$</span>distance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Mediana de la Distancia de Vuelo Fue:"</span>, Mediana_Distancia_de_vuelo, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Mediana de la Distancia de Vuelo Fue: 762 </code></pre>
</div>
</div>
<p>Al comparar estos datos con los promedios iniciales de &nbsp;tiempo y distancia (141.8 min y 977.5 millas), la brecha es notable: la mediana es considerablemente más baja en ambos casos.</p>
<p>Esta diferencia técnica se conoce como&nbsp;<strong>sesgo positivo</strong>&nbsp;(o asimetría a la derecha). Lo que nos dice es que la “experiencia típica” en un aeropuerto de NYC es mucho más corta de lo que el promedio sugiere. Mientras que el promedio se ve arrastrado hacia arriba por los vuelos masivos a lugares como Londres, París o Los Ángeles, la mediana de 121 minutos nos revela que el 50% de los vuelos en Nueva York duran en realidad&nbsp;<strong>2 horas o menos</strong>.</p>
<p>En términos de distancia, una mediana de 762 millas es muy reveladora, es decir, &nbsp;para ponerlo en perspectiva, esa es casi la distancia exacta entre Nueva York y ciudades como Charlotte o Detroit. El hecho de que la mediana sea aproximadamente 215 millas menor que el promedio, confirma que el volumen masivo de operaciones en 2023 estuvo concentrado en vuelos regionales de corta distancia. Políticamente, esto explica porque la congestión en los cielos de Nueva York es tan difícil de resolver, pues no es que hayan muchos aviones desplazándose a sitios alejados, sino que hay mucha densidad de aviones haciendo trayectos cortos simultáneamente, lo que satura los canales de comunicación y las rutas de ascenso.</p>
<p>Para complementar el análisis de la eficiencia y el comportamiento de las rutas, es fundamental cruzar los tiempos y distancias con el volumen de operaciones mensuales, ya que la saturación de las pistas no se distribuye de forma equitativa a lo largo del año. Entender la estacionalidad es clave porque un sistema que maneja cerca de 40,000 operaciones en un solo mes se comporta de manera distinta a uno con menos tráfico, afectando directamente la variabilidad de esos 121 minutos que vimos en la mediana. Al identificar el punto de máxima presión operativa, podemos determinar si los recursos de los aeropuertos de NYC están alineados con los picos de demanda de los pasajeros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>Diferencia_vuelos <span class="ot">&lt;-</span> <span class="fu">c</span>(Tiempo_promedio_vuelo <span class="sc">-</span> Mediana_tiempo_de_vuelo)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Diferencia de Vuelos Fue:"</span>, Diferencia_vuelos, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Diferencia de Vuelos Fue: 20.82026 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>Diferencia_Distancia <span class="ot">&lt;-</span> <span class="fu">c</span>(Distancia_promedio <span class="sc">-</span> Mediana_Distancia_de_vuelo)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Diferencia de Distancia Fue:"</span>, Diferencia_Distancia, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Diferencia de Distancia Fue: 215.503 </code></pre>
</div>
</div>
<p>Estas cifras indican que los datos presentan una&nbsp;<strong>asimetría positiva</strong>. Esto significa que, aunque el promedio nos diga que un vuelo dura 2 horas y 21 minutos, la realidad es que&nbsp;<strong>el 50% de los vuelos de Nueva York duran 2 horas o menos</strong>; el promedio se ve más alto simplemente porque hay unos pocos vuelos muy largos que “pesan” mucho en el cálculo. Esto nos dice que la&nbsp;<strong>Mediana</strong>&nbsp;nos permite describir con mayor presicion un vuelo “típico” de NYC.</p>
<p>Ahora queremos saber en que mes hubo mas vuelos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>meses_vuelo <span class="ot">&lt;-</span> <span class="fu">table</span>(flights<span class="sc">$</span>month)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>meses_vuelo[<span class="fu">which.max</span>(meses_vuelo)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    3 
39514 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El mes con más vuelos fue el mes"</span>, <span class="fu">names</span>(<span class="fu">which.max</span>(<span class="fu">table</span>(flights<span class="sc">$</span>month))), </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"con un total de"</span>, <span class="fu">max</span>(<span class="fu">table</span>(flights<span class="sc">$</span>month)), <span class="st">"vuelos."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El mes con más vuelos fue el mes 3 con un total de 39514 vuelos.</code></pre>
</div>
</div>
<p>El hecho de que&nbsp;<strong>marzo (mes 3) sea el mes con más vuelos, alcanzando un total de 39,514</strong>, revela una dinámica económica y social muy particular de la región noreste. Históricamente, marzo es el mes del&nbsp;<em>Spring Break</em>&nbsp;y el inicio de la planificación de negocios del segundo trimestre, lo que genera una “tormenta perfecta” de viajeros de placer hacia destinos cálidos y viajeros corporativos reactivando sus agendas tras el invierno. Políticamente, este volumen masivo en marzo de 2023 puso a prueba la resiliencia de la FAA ante la falta de controladores, ya que gestionar más de 1,200 vuelos diarios en un espacio aéreo tan restringido como el de Nueva York deja un margen de error casi nulo para el mantenimiento de las pistas y la gestión de puertas de embarque.</p>
<p>Desde un punto de vista estadístico, este pico de tráfico en marzo ayuda a explicar por qué el promedio de tiempo de vuelo tiende a ser más alto que la mediana. Con casi 40,000 vuelos compitiendo por espacio, las colas de salida en aeropuertos como JFK o Newark se vuelven mucho más largas, provocando que un grupo considerable de vuelos sufra retrasos por congestión en tierra. Estos vuelos “atrapados” son los que empujan el promedio hacia los 141 minutos, mientras que la mediana de 121 minutos nos sigue recordando que, a pesar del volumen masivo de marzo, la mitad de la operación logró mantenerse dentro de los parámetros estándar de tiempo.</p>
<p>Para profundizar en la precisión del comportamiento típico de los vuelos en 2023, es necesario introducir la&nbsp;<strong>media geométrica</strong>&nbsp;tanto del tiempo como de la distancia. A diferencia del promedio aritmético, la media geométrica es menos sensible a los valores extremos y es ideal para datos que presentan variaciones porcentuales o crecimientos, permitiéndonos encontrar un valor central que represente mejor el “rendimiento consolidado” de la red aeroportuaria. Este cálculo es vital para suavizar el impacto de los vuelos excepcionalmente largos que distorsionan la realidad operativa de la mayoría de los trayectos en Nueva York.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Media_Geometrica_vuelos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(flights<span class="sc">$</span>air_time), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Media Geometrica de Vuelos Fue:"</span>, Media_Geometrica_vuelos, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Media Geometrica de Vuelos Fue: 117.2645 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Media_Geometrica_Distancia <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(flights<span class="sc">$</span>distance), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Media Geometrica de Distancia Fue:"</span>, Media_Geometrica_Distancia, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Media Geometrica de Distancia Fue: 751.1687 </code></pre>
</div>
</div>
<p>La&nbsp;<strong>Media Geométrica de Vuelos de 117.26 minutos</strong>&nbsp;nos ofrece una visión más realista que el promedio de 141 minutos. Este dato nos indica que, tras mitigar el efecto de los retrasos masivos y los vuelos transcontinentales, el tiempo de vuelo “central” de la operación es notablemente más ágil. Socialmente, esto sugiere que el sistema aeroportuario de NYC, a pesar de su fama de caótico, logra procesar la mayoría de sus viajes en un rango cercano a las dos horas, lo que valida la eficiencia de los corredores aéreos de corta y mediana distancia que alimentan la economía de la ciudad.</p>
<p>Por su parte, la&nbsp;<strong>Media Geométrica de Distancia de 751.16 millas</strong>&nbsp;confirma que el núcleo de la red aérea de Nueva York está anclado en destinos regionales. Mientras que el promedio de 977 millas nos hacía mirar hacia destinos más lejanos, este valor sitúa el centro de masa de los vuelos en ciudades del radio cercano-medio (como el corredor hacia Ohio o las Carolinas). Estadísticamente, esto demuestra que la infraestructura de 2023 estuvo dedicada primordialmente a sostener la conectividad doméstica de alta frecuencia, dejando los vuelos de larga distancia como una periferia importante pero no dominante en el volumen diario.</p>
<p>Para entender la eficiencia real del movimiento, ahora buscamos conocer la&nbsp;<strong>velocidad de vuelo</strong>&nbsp;utilizando la&nbsp;<strong>media armónica</strong>, ya que esta es la medida adecuada cuando trabajamos con razones o tasas (como millas por minuto). La media armónica es fundamental porque pondera de forma más justa los valores bajos, lo que en aviación equivale a los periodos de baja velocidad por congestión o rodaje que afectan drásticamente al tiempo total y a su vez nos permite analizar si el resultado es o no una métrica de eficiencia que relaciona la distancia recorrida por unidad de tiempo bajo una perspectiva de rendimiento crítico.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>velocidad <span class="ot">&lt;-</span> flights<span class="sc">$</span>distance <span class="sc">/</span> flights<span class="sc">$</span>air_time</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media Armónica:"</span>, <span class="dv">1</span> <span class="sc">/</span> <span class="fu">mean</span>(<span class="dv">1</span> <span class="sc">/</span> velocidad, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Media Armónica: 6.335551</code></pre>
</div>
</div>
<p>Al analizar esta&nbsp;<strong>Media Armónica de 6.33</strong>, observamos una tasa de progresión que refleja las dificultades del espacio aéreo de Nueva York. Al ser menor que la media aritmética, nos está señalando que los vuelos pasan una cantidad significativa de tiempo en fases de “baja productividad”, como las esperas en pista de JFK o las aproximaciones lentas debido al tráfico denso de marzo. Políticamente, este número es un indicador de la necesidad de modernizar el sistema NextGen de navegación, ya que una media armónica baja sugiere que el sistema no logra mantener una fluidez constante, penalizando el tiempo total del pasajero.</p>
<p>Continuando con el desglose, introducimos la&nbsp;<strong>media aritmética</strong>&nbsp;aplicada a la velocidad para compararla con los valores anteriores. Este dato es el promedio estándar que todos conocemos y nos sirve para establecer una línea base de la rapidez esperada en condiciones ideales. La cual con su resultado nos permitirá observar la brecha entre el promedio simple y el rendimiento armónico, lo cual es una medida indirecta de la variabilidad y la resistencia que ofrece el entorno de NYC a la libre circulación de las aeronaves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>velocidad <span class="ot">&lt;-</span> flights<span class="sc">$</span>distance <span class="sc">/</span> flights<span class="sc">$</span>air_time</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media Aritmetica:"</span>, <span class="fu">mean</span>(velocidad, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Media Aritmetica: 6.518824 </code></pre>
</div>
</div>
<p>El análisis de esta&nbsp;<strong>Media Aritmética de 6.51</strong>&nbsp;muestra que, en promedio, los aviones mantienen una relación distancia-tiempo ligeramente superior a la tasa armónica, pero aún dentro de un rango que delata la congestión urbana. Esta cifra representa la “cara visible” del rendimiento, la que las aerolíneas suelen usar en sus informes de cumplimiento. Sin embargo, la diferencia entre 6.51 y 6.33 confirma estadísticamente que existen fluctuaciones importantes; no todos los vuelos alcanzan esa velocidad promedio, y las ineficiencias del sistema tiran hacia abajo del rendimiento real percibido por la operación técnica.</p>
<p>Ahora queremos analizar los retrasos con mayor rigor usando la&nbsp;<strong>media de orden h o media cuadrática (h=2)</strong>. Esta medida es sumamente potente en el análisis de errores o desviaciones, ya que eleva los valores al cuadrado, otorgando un peso mucho mayor a los retrasos grandes. Es necesaria para la seguridad aérea y la gestión de calidad, porque en un aeropuerto no es lo mismo tener diez retrasos de 5 minutos que uno de 50 minutos; la media cuadrática nos permite castigar estadísticamente esos fallos graves para entender la verdadera magnitud del problema.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Retrasos_Vuelos <span class="ot">&lt;-</span> flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>dep_delay <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(flights<span class="sc">$</span>dep_delay)]</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>Media_Cuadratica <span class="ot">&lt;-</span> (<span class="fu">mean</span>(Retrasos_Vuelos<span class="sc">^</span>h))<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>h)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Media Cuadrática para h = 2 es:"</span>, Media_Cuadratica, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Media Cuadrática para h = 2 es: 93.04122 </code></pre>
</div>
</div>
<p>Esta&nbsp;<strong>Media Cuadrática de 93.04</strong>&nbsp;es significativamente alta, lo que indica que los retrasos en Nueva York durante 2023 no fueron solo “pequeñas molestias” de unos pocos minutos. Al ser un valor que prioriza los extremos, nos revela que los aeropuertos sufrieron incidentes de gran magnitud que impactan la operación mucho más de lo que el promedio simple dejaría ver. Este dato es crucial para las autoridades políticas, pues sugiere que el sistema es vulnerable a eventos disruptivos (clima, fallos técnicos) que generan retrasos muy largos, penalizando severamente la fiabilidad del transporte aéreo en la región.</p>
<p>Para poner nombre y apellido a estas métricas, introducimos una&nbsp;<strong>comparativa entre aerolíneas</strong>&nbsp;para identificar cuál presentó el mayor grado de incumplimiento. El gráfico de cajas y bigotes (<em>boxplot</em>) que proporcionaremos a continuación nos permite visualizar no solo el retraso central, sino la dispersión y los valores atípicos de cada compañía en 2023. Esta visualización es la herramienta definitiva para discernir si los retrasos son un problema generalizado del aeropuerto o si existen deficiencias operativas específicas en ciertas empresas que operan en los nodos de Nueva York.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(carrier) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">q3 =</span> <span class="fu">quantile</span>(dep_delay, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">p90 =</span> <span class="fu">quantile</span>(dep_delay, <span class="fl">0.90</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(airlines, <span class="at">by =</span> <span class="st">"carrier"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(p90))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 5
   carrier mediana    q3   p90 name                  
   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                 
 1 F9            8  44    98   Frontier Airlines Inc.
 2 B6            0  27    85   JetBlue Airways       
 3 NK           -2  16    67   Spirit Air Lines      
 4 HA            3  19    64   Hawaiian Airlines Inc.
 5 UA           -1  16    61   United Air Lines Inc. 
 6 OO           -2   8    60.7 SkyWest Airlines Inc. 
 7 DL           -1  10    47   Delta Air Lines Inc.  
 8 WN            3  18    45   Southwest Airlines Co.
 9 AA           -3   5    43   American Airlines Inc.
10 MQ            0  14.8  42.7 Envoy Air             
11 AS           -3   9    42   Alaska Airlines Inc.  
12 9E           -4   1    33   Endeavor Air Inc.     
13 YX           -5  -1    23   Republic Airline      
14 G4           -5   0    14   Allegiant Air         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(flights, <span class="fu">aes</span>(<span class="at">x =</span> carrier, <span class="at">y =</span> dep_delay)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"red"</span>, <span class="at">outlier.shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">200</span>) <span class="sc">+</span> <span class="co"># Limitamos a 200 min para que se vea bien la caja</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Comparación de Retrasos por Aerolínea"</span>, </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Aerolínea"</span>, <span class="at">y =</span> <span class="st">"Retraso (minutos)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 271584 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Analizis-aereolineas_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar el gráfico, destaca que aerolíneas como&nbsp;<strong>Frontier (F9) y JetBlue (B6)</strong>&nbsp;muestran cajas más amplias y una densidad abrumadora de puntos rojos (valores atípicos), lo que indica una inestabilidad operativa mayor en comparación con compañías como Alaska (AS) o Hawaiian (HA), que tienen cajas más compactas. Especialmente en Nueva York, JetBlue (B6) tiene una presencia masiva, y su gráfica muestra una mediana de retraso más alta que sus competidores directos, con una “cola” de puntos rojos que llega hasta los 200 minutos. Esto sugiere que las aerolíneas de bajo costo o con bases principales en NYC sufren más la congestión, posiblemente debido a que tienen menos margen de maniobra en sus flotas para absorber las demoras en cascada.</p>
<p>Enfocándonos en el detalle, analizamos específicamente a&nbsp;<strong>Frontier (F9) y JetBlue (B6)</strong>&nbsp;mediante su desviación estándar y varianza. Estos datos son vitales para entender la&nbsp;<strong>predictibilidad</strong>: una desviación estándar alta significa que el pasajero nunca sabe si su vuelo saldrá a tiempo o con tres horas de demora.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>Desviacion_Estandar_F9 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">sd</span>(flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"F9"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>Desviacion_Estandar_B6 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">sd</span>(flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"B6"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>Varianza_Muestral_F9 <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="fu">var</span>(flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"F9"</span> ], <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>Varianza_Muestral_B6 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">var</span>(flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"B6"</span> ], <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Desviacion Estandar de F9 Fue:"</span>, Desviacion_Estandar_F9,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Desviacion Estandar de F9 Fue: 97.0781 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Desviacion Estandar de B6 Fue:"</span>, Desviacion_Estandar_B6,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Desviacion Estandar de B6 Fue: 59.42489 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Varianza Muestral de F9 Fue:"</span>, Varianza_Muestral_F9,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Varianza Muestral de F9 Fue: 9424.157 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La Varianza Muestral de F9 Fue:"</span>, Varianza_Muestral_B6,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La Varianza Muestral de F9 Fue: 3531.318 </code></pre>
</div>
</div>
<p>El análisis de estos valores revela una brecha de consistencia enorme.&nbsp;<strong>Frontier (F9)</strong>&nbsp;posee una varianza y desviación casi el doble de grandes que las de JetBlue, lo que estadísticamente la convierte en la aerolínea más impredecible de Nueva York. Para un analista, una desviación de 97 minutos es alarmante, ya que implica que la incertidumbre sobre el horario es casi igual al tiempo de vuelo promedio. Aunque JetBlue (B6) también tiene valores altos, su menor varianza (3531.31) indica que, aunque se retrasa con frecuencia, sus retrasos están algo más agrupados en comparación con el caos errático de Frontier.</p>
<p>Para normalizar esta comparación, introducimos el&nbsp;<strong>coeficiente de variación (CV)</strong>&nbsp;y la&nbsp;<strong>desviación media</strong>. El CV es fundamental porque nos permite comparar la variabilidad de dos grupos con promedios distintos, expresándola como un porcentaje. Es la medida definitiva para saber qué tan “relativamente” inestable es cada aerolínea en proporción a su propio tiempo de operación, mientras que la desviación media nos da el promedio absoluto de la distancia de cada vuelo respecto a la norma.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(carrier <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"F9"</span>, <span class="st">"B6"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(carrier) <span class="sc">%&gt;%</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">promedio =</span> <span class="fu">mean</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">varianza_muestral =</span> <span class="fu">var</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">desviacion_estandar =</span> <span class="fu">sd</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  carrier promedio varianza_muestral desviacion_estandar
  &lt;chr&gt;      &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;
1 B6          23.8             3531.                59.4
2 F9          35.7             9424.                97.1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>Retrasos_F9 <span class="ot">&lt;-</span> flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"F9"</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(flights<span class="sc">$</span>dep_delay)]</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>Coeficiente_de_Variacion_F9 <span class="ot">&lt;-</span> (<span class="fu">sd</span>(Retrasos_F9) <span class="sc">/</span> <span class="fu">mean</span>(Retrasos_F9)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>Desviacion_Media_F9 <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(Retrasos_F9 <span class="sc">-</span> <span class="fu">mean</span>(Retrasos_F9)))</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Aereolinea (F9):</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"El Coeficiente de Variacion Fue:"</span>, Coeficiente_de_Variacion_F9, <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"La Desviación Media Fue:"</span>, Desviacion_Media_F9, <span class="st">"min"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Aereolinea (F9):
 El Coeficiente de Variacion Fue: 271.6126 %
 La Desviación Media Fue: 46.7388 min</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>Retrasos_B6 <span class="ot">&lt;-</span> flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"B6"</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(flights<span class="sc">$</span>dep_delay)]</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>Coeficiente_de_Variacion_B6 <span class="ot">&lt;-</span> (<span class="fu">sd</span>(Retrasos_B6) <span class="sc">/</span> <span class="fu">mean</span>(Retrasos_B6)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>Desviacion_Media_B6 <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(Retrasos_B6 <span class="sc">-</span> <span class="fu">mean</span>(Retrasos_B6)))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Aereolinea (B6):</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"El Coeficiente de Variacion Fue:"</span>, Coeficiente_de_Variacion_B6, <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"La Desviación Media Fue:"</span>, Desviacion_Media_B6, <span class="st">"min"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Aereolinea (B6):
 El Coeficiente de Variacion Fue: 249.918 %
 La Desviación Media Fue: 36.46711 min</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(carrier <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"F9"</span>, <span class="st">"B6"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(carrier) <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">promedio =</span> <span class="fu">mean</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Cálculo del CV</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">CV =</span> (sd <span class="sc">/</span> promedio) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Cálculo de la Desviación Media</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">desviacion_media =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(dep_delay <span class="sc">-</span> <span class="fu">mean</span>(dep_delay, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  carrier promedio    sd    CV desviacion_media
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;            &lt;dbl&gt;
1 B6          23.8  59.4  250.             36.5
2 F9          35.7  97.1  272.             46.7</code></pre>
</div>
</div>
<p>En el caso de&nbsp;<strong>Frontier (F9)</strong>, el&nbsp;<strong>Coeficiente de Variación de 271.61%</strong>&nbsp;es astronómico, confirmando que la variabilidad de sus retrasos es casi tres veces superior a su valor promedio; esto es un indicador de una operación extremadamente volátil en 2023. La&nbsp;<strong>Desviación Media de 46.73 min</strong>&nbsp;refuerza esto, indicando que, en promedio, cualquier vuelo de Frontier se aleja casi 47 minutos de su hora prevista. Socialmente, esto se traduce en una experiencia de usuario frustrante, donde la puntualidad es la excepción y no la regla, lo que puede deberse a que Frontier, al tener menos vuelos en NYC que JetBlue, sufre más el impacto de cada retraso individual.</p>
<p>Por otro lado,&nbsp;<strong>JetBlue (B6)</strong>&nbsp;presenta un&nbsp;<strong>Coeficiente de Variación de 249.91%</strong>&nbsp;y una&nbsp;<strong>Desviación Media de 36.46 min</strong>. Aunque estas cifras siguen siendo altas y reflejan la complejidad de operar su base principal en un entorno saturado como JFK, son menores que las de Frontier. Esto indica que JetBlue, a pesar de tener una red mucho más compleja y masiva en Nueva York, logra mantener un control ligeramente superior sobre la dispersión de sus tiempos. Sus retrasos están más “estandarizados”, lo cual, aunque negativo para el pasajero, permite a la aerolínea gestionar mejor las expectativas logísticas que la aleatoriedad extrema de F9.</p>
<p>Finalmente, calculamos las&nbsp;<strong>medidas de forma sesgo y curtosis</strong>. Estas nos dicen cómo se distribuyen los errores: el sesgo indica si los retrasos se inclinan hacia un lado, y la curtosis mide qué tan “puntiaguda” es la distribución (qué tan frecuentes son los valores extremos). Para&nbsp;<strong>Frontier (F9)</strong>, el&nbsp;<strong>Sesgo de 6.95</strong>&nbsp;y la&nbsp;<strong>Curtosis de 64.54</strong>&nbsp;son valores extremos que describen una distribución con una cola larguísima a la derecha. Esto significa que Frontier tiene una cantidad desproporcionada de retrasos “monstruosos” que ocurren con una frecuencia mucho mayor de lo que predeciría una distribución normal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>Retrasos_F9 <span class="ot">&lt;-</span> flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"F9"</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(flights<span class="sc">$</span>dep_delay)]</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>Sesgo_F9 <span class="ot">&lt;-</span> <span class="fu">skewness</span>(Retrasos_F9)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>Curtosis_F9 <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(Retrasos_F9)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Análisis de Forma para Frontier (F9):</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sesgo (Skewness):"</span>, Sesgo_F9, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Curtosis:"</span>, Curtosis_F9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Análisis de Forma para Frontier (F9):
 Sesgo (Skewness): 6.953438 
 Curtosis: 64.54483</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>Retrasos_B6 <span class="ot">&lt;-</span> flights<span class="sc">$</span>dep_delay[flights<span class="sc">$</span>carrier <span class="sc">==</span> <span class="st">"B6"</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(flights<span class="sc">$</span>dep_delay)]</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>Sesgo_B6 <span class="ot">&lt;-</span> <span class="fu">skewness</span>(Retrasos_B6)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>Curtosis_B6 <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(Retrasos_B6)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Análisis de Forma para JetBlue (B6):</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sesgo (Skewness):"</span>, Sesgo_B6, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Curtosis:"</span>, Curtosis_B6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Análisis de Forma para JetBlue (B6):
 Sesgo (Skewness): 3.993932 
 Curtosis: 27.83981</code></pre>
</div>
</div>
<p>Para&nbsp;<strong>Frontier (F9)</strong>, el&nbsp;<strong>Sesgo de 6.95</strong>&nbsp;y la&nbsp;<strong>Curtosis de 64.54</strong>&nbsp;representan valores estadísticamente extremos que describen una operación sumamente irregular. Un sesgo tan alto hacia la derecha indica que, aunque la mayoría de los vuelos intentan cumplir un horario, existe una cantidad desproporcionada de casos donde los retrasos se extienden por muchísimas horas, alejándose drásticamente de la normalidad. Por su parte, una curtosis de 64.54 (considerada leptocúrtica extrema) revela que la probabilidad de sufrir un “retraso monstruo” en Frontier no es un evento raro o aislado, sino una característica intrínseca de su distribución de datos en 2023. Para un analista, esto sugiere que Frontier carece de la resiliencia operativa necesaria para recuperarse rápidamente cuando algo sale mal en los congestionados aeropuertos de Nueva York, convirtiendo cualquier pequeño problema en una demora masiva para el pasajero.</p>
<p>Por otro lado, el análisis para&nbsp;<strong>JetBlue (B6)</strong>&nbsp;muestra un&nbsp;<strong>Sesgo de 3.99</strong>&nbsp;y una&nbsp;<strong>Curtosis de 27.83</strong>. Aunque estos valores siguen siendo elevados y reflejan la complejidad de operar su base principal en un entorno saturado como JFK, son significativamente menores que los de Frontier. Esto indica que la distribución de los retrasos en JetBlue es más “controlada”; aunque sus vuelos se retrasan con frecuencia, no alcanzan los niveles de deformación estadística de F9. Esto sugiere que los problemas de JetBlue están más relacionados con la saturación estructural del aeropuerto de Nueva York, mientras que los de Frontier parecen estar agravados por factores internos que disparan la severidad de los retrasos hacia valores atípicos mucho más extremos.</p>
<section id="conclusión-general-del-análisis-estadístico" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-general-del-análisis-estadístico">Conclusión General del Análisis Estadístico</h3>
<p>El análisis estadístico de la operación aeroportuaria de Nueva York en 2023 concluye que existe una profunda&nbsp;<strong>desconexión entre la programación teórica y la ejecución real</strong>&nbsp;de los vuelos, donde el uso de promedios simples (141.8 min) enmascara una realidad operativa dominada por trayectos regionales cortos (mediana de 121 min) severamente afectados por la congestión. La saturación del sistema alcanza su punto crítico en marzo, provocando ineficiencias en la progresión de vuelo —reflejadas en una media armónica de 6.33— y una vulnerabilidad sistémica ante retrasos de gran magnitud, los cuales impactan con especial agresividad a aerolíneas como&nbsp;<strong>Frontier y JetBlue</strong>. Mientras que Frontier presenta una volatilidad extrema y una probabilidad alarmante de sufrir retrasos “monstruo” (curtosis de 64.54), el sistema en su conjunto demuestra una&nbsp;<strong>falta de predictibilidad</strong>&nbsp;que penaliza al usuario, confirmando que la infraestructura actual y la gestión del tráfico aéreo han sido superadas por la demanda, convirtiendo la variabilidad extrema en la característica intrínseca del nodo aéreo más importante de Estados Unidos.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>